config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'units#index'
  resources :units, only: [:index, :show, :edit, :new]
  resources :users, only: [:index, :show, :edit, :new]
  resources :timecards #, only: [:show, :edit, :delete]

  post '/timecards/start'  => 'timecards#start', as: :timecards_start
  post '/timecards/finish' => 'timecards#finish', as: :timecards_finish

  namespace :admin do
    get '/', to: 'units#index'
    resources :units
    resources :users
  end
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_many :users
	has_many :timecards
end

app/controllers/admin/units_controller.rb
module Admin
	class UnitsController < ApplicationController
		before_action :verify_admin
                before_action :verify_super_admin, only: [:index, :new, :create]
		before_action :set_unit, only: [:show, :edit, :update]

		def index
                  @units = Unit.all.order(:name)
		end

		def new
			@unit = Unit.new
		end

		def create
			@unit = Unit.new(unit_params)

			if @unit.save
				redirect_to admin_units_path, notice: 'Unit successfully created'
			else
				render :new
			end
		end

		def update
			if @unit.update(unit_params)
				redirect_to admin_units_path, notice: 'Unit successfully updated'
			else
				render :edit
			end
		end

		def show
                  @users_data = []
                  for user in @unit.users.order(:last_name)
                    @users_data.append(DisplayTimecards.new(user).call)
                  end
		end
		
		private def set_unit
		  @unit = Unit.find(params[:id])
		end

		private def unit_params
			d = params.require(:unit)
			{
				name: d['name'],
				city: d['city'],
				state: d['state'],
				phone_number: d['phone_number']
			}
		end

    private def verify_super_admin
      unless current_user.super_admin?
        flash[:alert] = 'You do not have sufficient access to do that action'
        redirect_to root_path
      end
    end

    private def verify_admin
      unless current_user.admin?
        flash[:alert] = 'You do not have sufficient access to do that action'
        redirect_to root_path
      end
    end
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show]

  def index
    if current_user.super_admin?
      @units = Unit.all.order(:name)
    else
      redirect_to unit_path(current_user.unit_id)
    end
  end

  def show
    @users_data = []
    @users = @unit.users.where(active: true).order(:last_name)
    #for user in @unit.users.where(active: true).order(:last_name)
      #@users_data.append(DisplayTimecards.new(user).call)
    #end
  end
	
  private def set_unit
    @unit = Unit.where(id: params[:id]).first
  end
end

app/views/admin/units/edit.html.erb
<div class='page-header'>
  <h1>Edit Unit</h1>
</div>

<div class='well bs-component'>
  <%= form_for(@unit, url: admin_unit_path, method: :put, html: { class: 'form-horizontal', multipart: true}) do |f| %>
    <% if @unit.errors.any? %>
    <fieldset>
        <div class="alert" id="error_explanation">
          <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this @unit from being saved:</h2>

          <ul>
          <% @unit.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class='form-group'>
        <%= f.label :name, class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <%= f.text_field :name, class: 'form-control', required: true %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :city, class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <%= f.text_field :city, class: 'form-control', required: true %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :state, class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <%= f.text_field :state, class: 'form-control', required: true %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :phone_number, class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <%= f.text_field :phone_number, class: 'form-control', required: true %>
        </div>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    <fieldset>
  <% end %>
</div>

<script type="application/javascript">
$(document).ready( function() {
    $('#unit_name').focus().select();
});
</script>

app/views/admin/units/index.html.erb
  <%= link_to 'Add Unit', new_admin_unit_path, class: 'btn btn-primary' %>
<div class='page-header'>
	<table class='table table-striped table-hover' width=40%>
		<thead>
			<tr>
				<th><br></th>
				<th>Name</th>
				<th>City</th>
				<th>State</th>
				<th>Members</th>
			</tr>
		</thead>

		<tbody>
			<% @units.each do |unit| %>
				<tr>
					<td><%= link_to 'Edit', edit_admin_unit_path(unit.id) %></td>
  				<td><%= link_to unit.name, admin_unit_path(id: unit.id) %></td>
					<td><%= unit.city %></td>
					<td><%= unit.state %></td>
					<td><%= unit.users.count %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/admin/units/new.html.erb
<div class='page-header'>
  <h1>Create a New Unit</h1>
</div>

<div class='well bs-component'>
  <%= form_for(@unit, url: admin_units_path, html: { class: 'form-horizontal', multipart: true}) do |f| %>
    <% if @unit.errors.any? %>
    <fieldset>
        <div class="alert" id="error_explanation">
          <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this @unit from being saved:</h2>

          <ul>
          <% @unit.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class='form-group'>
        <%= f.label :name, class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <%= f.text_field :name, class: 'form-control', required: true %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :city, class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <%= f.text_field :city, class: 'form-control', required: true %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :state, class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <%= f.text_field :state, class: 'form-control', required: true %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :phone_number, class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <%= f.text_field :phone_number, class: 'form-control', required: true %>
        </div>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    <fieldset>
  <% end %>
</div>

<script type="application/javascript">
$(document).ready( function() {
    $('#unit_name').focus().select();
});
</script>

app/views/admin/units/show.html.erb
<div style="float: right;">
	<%= link_to 'View FY Totals', timecards_path(unit_id: params['id']), method: 'GET', class: 'btn btn-primary' %>
  <%= link_to 'Add User', new_admin_user_path(unit_id: @unit.id), class: 'btn btn-primary' %>
</div>

<div class='page-header'>
  <h2><%= @unit.name %></h2> 
  <h4><%= @unit.city %>, <%= @unit.state %></h4> 
  <h4><%= @unit.phone_number %></h4> 
    <table class='table table-striped table-hover' width=60%>
      <thead>
        <tr>
          <th>Name</th>
					<th><br></th>
          <th>Email</th>
					<th><br></th>
					<th><br></th>
        </tr>
      </thead>

      <tbody>
        <% @users_data.each do |user| %>
          <tr>
						<td><%= user['user']['last_name'] + ", " + user['user']['first_name'] %></td>
						<td>
							<% if user['user']['active'] != true %>
								<i>Inactive</i>
							<% end %>
						</td>
						<td><%= user['user']['email'] %>
						<td><%= link_to "Show", admin_user_path(id: user['user']['id']), method: 'GET' %></td>
						<td><%= link_to "Edit", edit_admin_user_path(id: user['user']['id']), method: 'GET' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>