config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'units#index'
  resources :units, only: [:index, :show, :edit, :new]
  resources :users, only: [:index, :show, :edit, :new]
  resources :timecards #, only: [:show, :edit, :delete]

  post '/timecards/start'  => 'timecards#start', as: :timecards_start
  post '/timecards/finish' => 'timecards#finish', as: :timecards_finish

  namespace :admin do
    get '/', to: 'units#index'
    resources :units
    resources :users
  end
end

app/models/timecard.rb
class Timecard < ActiveRecord::Base
    belongs_to :user
		belongs_to :unit

		validates :hours, numericality: true
		validates_presence_of :start_time, :hours
end

app/controllers/timecard_controller.rb
require 'pry'
require 'date'

class TimecardController < ApplicationController
  def index
    @timecards = Timecard.all
  end

  def create
    binding.pry
    Timecard.create({user_id: params[:user_id], start_time: params[:start_time], end_time: (params[:start_time] + (params[:hours]).hours) } )
  end

  def update
    binding.pry
    t = Timecard.find(params[:id])
    t.update_column(:end_time, t.start_time + (params[:hours]).hours)
  end

  def delete
    Timecard.destroy(params[:id])
  end

  def start
    #binding.pry
    @timecard = Timecard.create({user_id: params[:id], start_time: Time.now()})
    redirect_to main_index_path 
  end

  def finish
    #binding.pry
    Timecard.update(params[:id], {:end_time => Time.now})
    redirect_to main_index_path 
  end
end

app/controllers/timecards_controller.rb
require 'date'

class TimecardsController < ApplicationController
  before_action :set_timecard, only: [:show, :update, :finish, :destroy]

  def index
		if params.has_key?(:unit_id)
			@unit = Unit.find(params[:unit_id])
		else
    	@unit = Unit.find(current_user.unit_id)
		end
    @users_data = []

    if not params[:FY].nil? 
      @fy = Time.new(params[:FY])
    else
      @fy = Time.now
      if @fy.month > 9
        @fy += 1.year
      end
    end
		fy_filter = @fy.beginning_of_year - 3.months
    @earlier = false
    @later = false

    if Timecard.where("start_time < ?", fy_filter).size > 0
      @earlier = true
    end
    if Timecard.where("start_time > ?", (fy_filter + 1.year - 1.day)).size > 0
      @later = true
    end
    for user in @unit.users.where(active: true).order(:last_name)
      @users_data.append(DisplayTimecards.new(user, fy_filter).call)
    end
  end

  def new
		@user_id = params[:id]
    @timecard = Timecard.new
  end

  def create
    user_id = params[:user_id]
    unit_id = User.find(user_id)[:unit_id]
		start_time = create_start_time(params[:start_date], params[:start_time])
    @timecard =  Timecard.new({user_id: user_id, start_time: start_time, hours: params[:timecard][:hours], unit_id: unit_id } )
    if @timecard.save
      redirect_to admin_user_path(id: params[:user_id]), notice: "Your timecard was created successfully"
    else
			@user_id = user_id
      render :new
    end
  end

  def update
		@timecard = Timecard.find(params[:id])
    if @timecard.update(hours: params['timecard']['hours'])
			redirect_to admin_user_path(id: @timecard.user_id), notice: "Your timecard was updated successfully"
		else
			render :edit
		end
  end

  def edit
    @timecard = Timecard.find(params[:id])
  end

  def show 
    @timecard = Timecard.find(params[:id])
  end

  def destroy
    user_id=@timecard.user.id
    @timecard.destroy
    redirect_to admin_user_path(id: @timecard.user_id)
  end

  def start
    user_id = params[:id]
    unit_id = params[:unit_id]
    if Timecard.where(user_id: user_id).where(hours: 0).empty? 
      @timecard = Timecard.create({user_id: params[:id], start_time: Time.now(), hours: 0, unit_id: unit_id })
    end
    redirect_to unit_path unit_id 
  end

  def finish
    if not Timecard.where(user_id: @timecard.user.id).where(hours: 0).empty? 
			elapsed = Time.now - @timecard.start_time
			if elapsed > 18 
				@timecard.update(hours: ((Time.now - @timecard.start_time)/1.hours).round(2))
			else
				@timecard.destroy
			end
		end
    redirect_to unit_path @timecard.user.unit.id 
  end 

	private 
	
	def set_timecard
    @timecard = Timecard.find(params[:id])
  end

	def create_start_time(date, time)
		begin
			Time.strptime("#{date} #{time}", '%m/%d/%Y %I:%M %p')
		rescue ArgumentError
			nil
		end
	end
end

app/views/timecards/edit.html.erb
<div class='page-header'>
  <h1>Editing Timecard</h1>
</div>

<div class='well bs-component'>
  <%= form_for(@timecard, url: timecard_path, method: :put, html: { class: 'form-horizontal', multipart: true}) do |f| %>
    <% if @timecard.errors.any? %>
    	<fieldset>
        <div id="error_explanation">
          <h2><%= pluralize(@timecard.errors.count, "error") %> prohibited this @timecard from being saved:</h2>

          <ul>
          <% @timecard.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

			<div class='form-group'>
        <%= f.label :start_date, "Date", class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <div class="input-group bootstrap-timepicker timepicker">
						<input type="text" data-provide="datepicker" class="form-control" name="timecard[start_time]" value="<%= @timecard.start_time.strftime('%m/%d/%Y') %>">
            <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
          </div>
        </div>
			</div>

      <div class='form-group'>
        <%= f.label :start_time, "Start Time (ZULU)", class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <div class="input-group bootstrap-timepicker timepicker">
            <input id="timepicker" type="text" class="form-control" name='start_time'>
            <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
          </div>
        </div>
      </div>
			
      <div class='form-group'>
        <%= f.label :hours, class: 'col-lg-2' %>
          <div class='col-lg-10'>
          <%= f.text_field :hours, class: 'form-control', required: true %>
        </div>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    <fieldset>
  <% end %>
</div>
<script type="application/javascript">
$(document).ready( function() {
    $('#timecard_hours').focus().select();
});
</script>

app/views/timecards/index.html.erb
<div class='page-header'>
	<div style="float: right;">
  	<%= link_to 'Download as .xlsx', users_path(format: :xlsx, unit_id: params['unit_id']), class: 'btn btn-primary' %>
	</div>
  <h2><%= @unit.name %></h2> 
  <h4><%= @unit.city %>, <%= @unit.state %></h4> 
  <h4><%= @unit.phone_number %></h4> 
  <center><h2>
  <% if @earlier %>
    <%= link_to '<<', timecards_path(FY: (@fy - 1.year).year, unit_id: params['unit_id']) %> 
  <% end %>
  FY <%= @fy.year %> 
  <% if @later %>
    <%= link_to '>>', timecards_path(FY: (@fy + 1.year).year, unit_id: params['unit_id']) %>
  <% end %>
  </h2></center>
	
	<table class='table table-striped table-hover' width=60%>
		<thead>
			<tr>
				<th>Name</th>
				<th>Oct</th>
				<th>Nov</th>
				<th>Dec</th>
				<th>Jan</th>
				<th>Feb</th>
				<th>Mar</th>
				<th>Apr</th>
				<th>May</th>
				<th>Jun</th>
				<th>Jul</th>
				<th>Aug</th>
				<th>Sep</th>
				<th>FY</th>
			</tr>
		</thead>

		<tbody>
			<% @users_data.each do |user| %>
				<tr>
					<td><%= link_to user['user']['last_name'] + ", " + user['user']['first_name'], user_path(id: user['user']['id']), method: 'GET' %></td>
					<td><%= user['oct'] %></td>
					<td><%= user['nov'] %></td>
					<td><%= user['dec'] %></td>
					<td><%= user['jan'] %></td>
					<td><%= user['feb'] %></td>
					<td><%= user['mar'] %></td>
					<td><%= user['apr'] %></td>
					<td><%= user['may'] %></td>
					<td><%= user['jun'] %></td>
					<td><%= user['jul'] %></td>
					<td><%= user['aug'] %></td>
					<td><%= user['sep'] %></td>
					<td><%= user['fy'] %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/timecards/new.html.erb
<div class='page-header'>
  <h1>New Timecard</h1>
</div>

<div class='well bs-component'>
  <%= form_for(@timecard, url: timecards_path, html: { class: 'form-horizontal', multipart: true}) do |f| %>
    <% if @timecard.errors.any? %>
    	<fieldset>
        <div id="error_explanation">
          <h2><%= pluralize(@timecard.errors.count, "error") %> prohibited this timecard from being saved:</h2>

          <ul>
          <% @timecard.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class='form-group'>
        <%= f.label :start_date, "Date", class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <div class="input-group bootstrap-timepicker timepicker">
            <input type="text" data-provide="datepicker" class="form-control" name="start_date">
            <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
          </div>
        </div>
      </div>

			<div class='form-group'>
        <%= f.label :start_time, "Start Time (ZULU)", class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <div class="input-group bootstrap-timepicker timepicker">
            <input id="timepicker" type="text" class="form-control" name='start_time'>
            <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
          </div>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :hours, class: 'col-lg-2' %>
          <div class='col-lg-10'>
						<%= f.text_field :hours, as: :integer,	class: 'form-control', required: true %>
        </div>
      </div>
      
      <%= hidden_field_tag "user_id", @user_id %>

      <div class="actions">
        <%= f.submit %>
      </div>
    <fieldset>
  <% end %>
</div>
<script type="application/javascript">
$(document).ready( function() {
    $('#timecard_hours').focus().select();
});
</script>

app/views/timecards/show.html.erb
<%= link_to 'Back to User', user_path(@timecard.user.id), class: 'btn btn-primary' %> 

<div class='page-header'>
	<h3>Start Date: <%= @timecard.start_time %></h3>
	<h3>Hours: <%= @timecard.hours %></h3>
<%= link_to 'Delete Timecard', timecard_path(@timecard.id), method: :delete, class: 'btn btn-primary' %> 
</div>