config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'units#index'
  resources :units, only: [:index, :show, :edit, :new]
  resources :users, only: [:index, :show, :edit, :new]
  resources :timecards #, only: [:show, :edit, :delete]

  post '/timecards/start'  => 'timecards#start', as: :timecards_start
  post '/timecards/finish' => 'timecards#finish', as: :timecards_finish

  namespace :admin do
    get '/', to: 'units#index'
    resources :units
    resources :users
  end
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_many :users
	has_many :timecards
end

app/controllers/admin/units_controller.rb
module Admin
	class UnitsController < ApplicationController
		before_action :verify_admin
                before_action :verify_super_admin, only: [:index, :new, :create]
		before_action :set_unit, only: [:show, :edit, :update]

		def index
                  @units = Unit.all.order(:name)
		end

		def new
			@unit = Unit.new
		end

		def create
			@unit = Unit.new(unit_params)

			if @unit.save
				redirect_to admin_units_path, notice: 'Unit successfully created'
			else
				render :new
			end
		end

		def update
			if @unit.update(unit_params)
				redirect_to admin_units_path, notice: 'Unit successfully updated'
			else
				render :edit
			end
		end

		def show
                  @users_data = []
                  for user in @unit.users.order(:last_name)
                    @users_data.append(DisplayTimecards.new(user).call)
                  end
		end
		
		private def set_unit
		  @unit = Unit.find(params[:id])
		end

		private def unit_params
			d = params.require(:unit)
			{
				name: d['name'],
				city: d['city'],
				state: d['state'],
				phone_number: d['phone_number']
			}
		end

    private def verify_super_admin
      unless current_user.super_admin?
        flash[:alert] = 'You do not have sufficient access to do that action'
        redirect_to root_path
      end
    end

    private def verify_admin
      unless current_user.admin?
        flash[:alert] = 'You do not have sufficient access to do that action'
        redirect_to root_path
      end
    end
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show]

  def index
    if current_user.super_admin?
      @units = Unit.all.order(:name)
    else
      redirect_to unit_path(current_user.unit_id)
    end
  end

  def show
    @users_data = []
    @users = @unit.users.where(active: true).order(:last_name)
    #for user in @unit.users.where(active: true).order(:last_name)
      #@users_data.append(DisplayTimecards.new(user).call)
    #end
  end
	
  private def set_unit
    @unit = Unit.where(id: params[:id]).first
  end
end

app/views/units/index.html.erb
<div class='page-header'>
    <table class='table table-striped table-hover' width=40%>
      <thead>
        <tr>
          <th>Name</th>
          <th>Members</th>
        </tr>
      </thead>

      <tbody>
        <% @units.each do |unit| %>
          <tr>
            <td><%= link_to unit.name, unit_path(id: unit.id) %></td>
            <td><%= unit.users.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/units/show.html.erb
<div class='page-header'>
	<div style="float: right;">
		<%= link_to 'View FY Totals', timecards_path(unit_id: params['id']), method: 'GET', class: 'btn btn-primary' %>
	</div>
	<div>
		<h2><%= @unit.name %></h2> 
		<h4><%= @unit.city %>, <%= @unit.state %></h4> 
		<h4><%= @unit.phone_number %></h4> 
	</div>
	<table class='table table-striped table-hover' width=30%>
		<thead>
			<tr>
				<th><br></th>
				<th>Name</th>
			</tr>
		</thead>

		<tbody>
			<% @users.each do |user| %>
				<tr>
					<% if user.timecards.length == 0 or user.timecards.order(start_time: :desc).first.hours != 0 %>
					<td><%= link_to 'Punch In', timecards_start_path(id: user['id'], unit_id: params['id']), method: 'POST' %></td>
				<% else %>
					<% print(user['id']) %>
					<td><%= link_to 'Punch Out', timecards_finish_path(id: user.timecards.where(hours: 0).first.id), method: 'POST' %></td>
				<% end %>
					<td><%= link_to user['last_name'] + ", " + user['first_name'], user_path(id: user['id']), method: 'GET' %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>