config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'units#index'
  resources :units, only: [:index, :show, :edit, :new]
  resources :users, only: [:index, :show, :edit, :new]
  resources :timecards #, only: [:show, :edit, :delete]

  post '/timecards/start'  => 'timecards#start', as: :timecards_start
  post '/timecards/finish' => 'timecards#finish', as: :timecards_finish

  namespace :admin do
    get '/', to: 'units#index'
    resources :units
    resources :users
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :unit
  has_many :timecards
end

app/controllers/admin/users_controller.rb
require 'date'

module Admin
	class UsersController < ApplicationController
                before_action :verify_admin
		before_action :set_user, only: [:show, :edit]

		def index
			@users = User.all.order(last_name: :asc)
		end

		def new
			@user = User.new
		end

		def create
			user_details = params.require(:user)
			user = User.create!(
				first_name: user_details['first_name'],
				last_name: user_details['last_name'],
				email: user_details['email'],
				admin: user_details['admin'],
				super_admin: user_details['super_admin'],
				password: user_details['email'],
				unit_id: params['unit_id']
			)
			redirect_to admin_unit_path(id: params['unit_id']), notice: 'User successfully created'
		end

		def show
			@total = DisplayTimecards.new(@user).call 
			timecards = []
			#TODO don't need this anymore
			for timecard in @user.timecards.order(start_time: :desc) do
				record = {"start_time": timecard.start_time, "hours": timecard.hours, "id": timecard.id}
				timecards.append(record)
			end
			@timecards = timecards
		end

		def edit
		end

		def update
			@user = User.find(params[:id])
			user_details = params.require(:user)
			@user.update(
				first_name: user_details['first_name'],
				last_name: user_details['last_name'],
				email: user_details['email'],
				active: user_details['active'],
				admin: user_details['admin'],
				super_admin: user_details['super_admin']
			)
			redirect_to admin_user_path(id: @user.id), notice: "Update successful"
		end
		
		def user_params
			user_details = params.require(:user)
			{
				first_name: user_details['first_name'],
				last_name: user_details['last_name'],
				email: user_details['email'],
				active: user_details['active'],
				admin: user_details['admin'],
				super_admin: user_details['super_admin']
			}
		end

		private def set_user
			@user = User.find(params[:id])
		end

    private def verify_admin
      unless current_user.admin?
        flash[:alert] = 'You do not have sufficient access to do that action'
        redirect_to root_path
      end
    end
	end
end

app/controllers/users_controller.rb
require 'date'

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit]

  def index
    @Users = User.where(unit_id: params['unit_id']).order(last_name: :asc)
		respond_to do |format|
			format.html
			format.xlsx
		end
  end

  def show
    @total = DisplayTimecards.new(@user).call 
    timecards = []
    #TODO don't need this anymore
    for timecard in @user.timecards.order(start_time: :desc) do
      record = {"start_time": timecard.start_time, "hours": timecard.hours, "id": timecard.id}
      timecards.append(record)
    end
    @timecards = timecards
  end
  
  private def set_user
    @user = User.find(params[:id])
  end
end

app/views/admin/users/edit.html.erb
<%= link_to 'Back to Unit', admin_unit_path(@user.unit.id), class: 'btn btn-primary' %> 
<div class='well bs-component'>
  <%= form_for(@user, url: admin_user_path, method: :put, html: { class: 'form-horizontal', multipart: true}) do |f| %>
    <% if @user.errors.any? %>
    <fieldset>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>

          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class='form-group'>
        <%= f.label :first_name, class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <%= f.text_field :first_name, class: 'form-control', required: true %>
        </div>
			</div>

			<div class='form-group'>
        <%= f.label :last_name, class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <%= f.text_field :last_name, class: 'form-control', required: true %>
        </div>
			</div>

			<div class='form-group'>
        <%= f.label :email, class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <%= f.text_field :email, class: 'form-control', required: true %>
        </div>
			</div>

      <div class='form-group'>
        <%= f.label :admin, "Unit Administrator?", class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <%= f.check_box :admin, class: 'form-control' %>
        </div>
      </div>			

      <% if current_user.super_admin %>
        <div class='form-group'>
          <%= f.label :super_admin, "Site Administrator?", class: 'col-lg-2' %>
          <div class='col-lg-10'>
            <%= f.check_box :super_admin, class: 'form-control' %>
          </div>
        </div>			
      <% end %>

      <div class='form-group'>
        <%= f.label :active, class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <%= f.check_box :active, class: 'form-control' %>
        </div>
      </div>			
	
      <div class="actions">
        <%= f.submit %>
      </div>
    <fieldset>
  <% end %>
</div>

app/views/admin/users/new.html.erb
<div class='page-header'>
  <h1>Create a New User</h1>
</div>

<div class='well bs-component'>
	<%= form_for(@user, url: admin_users_path, html: { class: 'form-horizontal', multipart: true}) do |f|%>
    <% if @user.errors.any? %>
    <fieldset>
        <div class="alert" id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>

          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

			<div class='form-group'>
        <%= f.label :first_name, class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <%= f.text_field :first_name, class: 'form-control', required: true %>
        </div>
			</div>

			<div class='form-group'>
        <%= f.label :last_name, class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <%= f.text_field :last_name, class: 'form-control', required: true %>
        </div>
			</div>

			<div class='form-group'>
        <%= f.label :email, class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <%= f.text_field :email, class: 'form-control', required: true %>
        </div>
			</div>

      <div class='form-group'>
        <%= f.label :admin, "Unit Administrator?", class: 'col-lg-2' %>
        <div class='col-lg-10'>
          <%= f.check_box :admin, class: 'form-control' %>
        </div>
      </div>			

			<%= hidden_field_tag "unit_id", params['unit_id'] %>

      <div class="actions">
        <%= f.submit %>
      </div>
    <fieldset>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<%= link_to 'Back to Unit', admin_unit_path(@user.unit.id), class: 'btn btn-primary' %> 
<%= link_to 'Edit User', edit_admin_user_path(@user.id), class: 'btn btn-primary' %> 

<div class='page-header'>
<h1><%= @user.first_name %> <%= @user.last_name %>
  <% if !@user.active %>
    <i>Inactive</i>
  <% end %>
</h1>
  <p>
    <% if @user.super_admin %>
      <h4>Super Administrator</h4>
    <% elsif @user.admin %>
      <h4>Administrator</h4>
    <% end %>
    <%= @user.email %></p>
  <table valign=top width=100%>
    <tr>
      <th>Oct</th>
      <th>Nov</th>
      <th>Dec</th>
      <th>Jan</th>
      <th>Feb</th>
      <th>Mar</th>
      <th>Apr</th>
      <th>May</th>
      <th>Jun</th>
      <th>Jul</th>
      <th>Aug</th>
      <th>Sep</th>
      <th>FY</th>
    </tr>
    <tr>
      <td><%= @total['oct'] %></td>
      <td><%= @total['nov'] %></td>
      <td><%= @total['dec'] %></td>
      <td><%= @total['jan'] %></td>
      <td><%= @total['feb'] %></td>
      <td><%= @total['mar'] %></td>
      <td><%= @total['apr'] %></td>
      <td><%= @total['may'] %></td>
      <td><%= @total['jun'] %></td>
      <td><%= @total['jul'] %></td>
      <td><%= @total['aug'] %></td>
      <td><%= @total['sep'] %></td>
      <td><%= @total['fy'] %></td>
    </tr>
  </table>
</div>

<%= link_to 'Add Timecard', new_timecard_path(id: @user.id), class: 'btn btn-primary' %> 

<div class='page-header'>
    <h2>All Timecards</h2>
    <table valign=top width=50%>
        <tr>
          <th><br></th>
          <th><br></th>
          <th>Date</th>
          <th>Zulu Time</th>
          <th>Hours</th>
        </tr>
        <% @timecards.each do |timecard| %>
          <tr>
	    <td><%= link_to 'Edit', edit_timecard_path(timecard[:id]) %></td>
	    <td><%= link_to 'Delete', timecard_path(timecard[:id]), method: :delete %></td>
            <td><%= timecard[:start_time].to_date %></td>
            <td><%= timecard[:start_time].to_s(:time) %></td>
            <td><%= timecard[:hours] %></td>
          </tr>
        <% end %>
    </table>
</div>
  